@startuml
class CFitsIO {
+ functions()
}
hide CFitsIO circle
package EL_CfitsioWrapper {
class SomeNamespace {
+ functions()
}
}
hide SomeNamespace circle
package EL_FitsData {
class SomeDataClass {
+ data
}
}
package EL_FitsFile {
class SomeServiceClass {
+ methods()
}
}
SomeDataClass <- SomeServiceClass : create and use
SomeDataClass <-- SomeNamespace : create and use
SomeServiceClass --> SomeNamespace : call
SomeNamespace --> CFitsIO : call
@enduml