@startuml
class CFITSIO {
+ functions()
}
hide CFITSIO circle
package EleCfitsioWrapper {
class SomeNamespace {
+ functions()
}
}
hide SomeNamespace circle
package EleFitsData {
class SomeDataClass {
+ data
}
}
package EleFits {
class SomeServiceClass {
+ methods()
}
}
SomeDataClass <- SomeServiceClass : create and use
SomeDataClass <-- SomeNamespace : create and use
SomeServiceClass --> SomeNamespace : call
SomeNamespace --> CFITSIO : call
@enduml