@startuml
package EleFitsData {

Column <|-- VecColumn
Column <|-- PtrColumn
ColumnInfo -* Column

Raster <|-- VecRaster
Raster <|-- PtrRaster
Position -* Raster

class Position<n> {
+ indices
}

abstract class Raster<T, n> {
+ shape()
+ length<axis>()
+ size()
+ {abstract} data()
+ operator[](position)
+ index(position)
}

class VecRaster<T, n> {
- m_vec
+ data()
+ vector()
}

class PtrRaster<T, n> {
- m_data
+ data()
}

class Record<T> {
+ keyword
+ value
+ unit
+ comment
}

class ColumnInfo<T> {
+ name
+ unit
+ repeatCount
}

abstract class Column<T> {
+ info
+ {abstract} data()
+ elementCount()
+ rowCount()
}

class VecColumn<T> {
- m_vec
+ data()
+ vector()
}

class PtrColumn<T> {
- m_data
+ data()
}

}
@enduml