@startuml

package EL_FitsData {

Raster <|-- VecRaster
Raster <|-- VecRefRaster
Raster <|-- PtrRaster
Raster *- Position

Record -[hidden] Record

Column <|-- VecColumn
Column <|-- VecRefColumn
Column <|-- PtrColumn
ColumnInfo -* Column

class Position<n> {
}

abstract class Raster<T, n> {
+ shape
+ {abstract} data ()
+ operator [] (position)
+ length<axis> ()
+ size ()
+ index (position)
}

class VecRaster<T, n> {
- m_vec
+ VecRaster (shape, vector)
+ VecRaster (shape)
+ VecRaster ()
+ data ()
+ vector ()
}

class VecRefRaster<T, n> {
- m_ref
+ VecRefRaster (shape, vector)
+ data ()
+ vector ()
}

class PtrRaster<T, n> {
- m_data
+ PtrRaster (shape, data)
+ data ()
}

class Record<T> {
+ keyword
+ value
+ unit
+ comment
+ operator T ()
}

class ColumnInfo<T> {
+ name
+ unit
+ repeatCount
}

abstract class Column<T> {
+ info
+ {abstract} data ()
+ elementCount ()
+ rowCount ()
}

class VecColumn<T> {
- m_vec
+ VecColumn (info, vector)
+ VecColumn (info)
+ VecColumn ()
+ data ()
+ vector ()
}

class VecRefColumn<T> {
- m_ref
+ VecRefColumn (info, vector)
+ data ()
+ vector ()
}

class PtrColumn<T> {
- m_data
+ PtrColumn (info, rowCount, vector)
+ data ()
}

}

@enduml
