@startuml
actor "Jean-René" as User
box EleFits
participant SifFile
participant Hdu
participant ImageHdu
endbox
box EleCfitsioWrapper
participant "Cfitsio namespace" as CfitsioWrapper
endbox
box EleFitsData
participant Record
participant Raster
endbox
== SifFile file("file.fits"); ==
User -> SifFile* : create()
activate SifFile
SifFile -> CfitsioWrapper : open()
CfitsioWrapper --> SifFile : fitsfile*
SifFile --> User : SifFile
== auto &header = file.header(); ==
User -> SifFile : header()
SifFile -> Hdu* : create()
activate Hdu
Hdu --> SifFile : Hdu
SifFile --> User : Hdu
== int value = header.parseRecord<int>("KEYWORD"); ==
User -> Hdu : parseRecord()
Hdu -> CfitsioWrapper : parseRecord()
CfitsioWrapper -> Record* : create()
activate Record
Record --> CfitsioWrapper : Record
CfitsioWrapper --> Hdu : Record
Hdu --> User : Record
User -> Record : int()
Record --> User : value
destroy Record
== auto raster = file.readRaster<float>(); ==
User -> SifFile : readRaster()
SifFile -> ImageHdu* : create()
activate ImageHdu
ImageHdu --> SifFile : ImageHdu
SifFile -> ImageHdu : readRaster()
ImageHdu -> CfitsioWrapper : readRaster()
CfitsioWrapper -> Raster* : create()
activate Raster
Raster --> CfitsioWrapper : Raster
CfitsioWrapper --> ImageHdu : Raster
ImageHdu --> User : Raster
destroy ImageHdu
@enduml