# - Locate EleFits library
# Defines:
#
#  ELEFITS_FOUND
#  ELEFITS_INCLUDE_DIR
#  ELEFITS_INCLUDE_DIRS (not cached)
#  ELEFITS_LIBRARY
#  ELEFITS_LIBRARIES (not cached)

if(NOT ELEFITS_FOUND)

  find_path(ELEFITS_INCLUDE_DIR EleFits/MefFile.h
            HINTS ENV ELEFITS_ROOT_DIR ELEFITS_INSTALL_DIR
            PATH_SUFFIXES include)

  find_library(ELEFITS_LIBRARY EleFits
               HINTS ENV ELEFITS_ROOT_DIR ELEFITS_INSTALL_DIR
               PATH_SUFFIXES lib lib64)

  set(ELEFITS_LIBRARIES ${ELEFITS_LIBRARY})
  set(ELEFITS_INCLUDE_DIRS ${ELEFITS_INCLUDE_DIR})

  INCLUDE(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(ELEFITS DEFAULT_MSG ELEFITS_INCLUDE_DIRS ELEFITS_LIBRARIES)

  mark_as_advanced(ELEFITS_FOUND ELEFITS_INCLUDE_DIRS ELEFITS_LIBRARIES)

  list(REMOVE_DUPLICATES ELEFITS_LIBRARIES)
  list(REMOVE_DUPLICATES ELEFITS_INCLUDE_DIRS)

endif()
